# Cloud profile for Aiven MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-3ad9c4fb-yashbala9688-f5b9.a.aivencloud.com:22729/food_ordering_2?useSSL=true&requireSSL=true&createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${AIVEN_USERNAME:Kamaliga}
spring.datasource.password=${AIVEN_PASSWORD:AVNS_HYF_ZZvfuzP5JY5_TMk}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
